apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: execution-service
  namespace: monitoring
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - oj

  selector:
    matchLabels:
      app: execution

  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
