apiVersion: v1
kind: Service
metadata:
  name: submissions-service
  namespace: oj
  labels:
    app: submissions
spec:
  selector:
    app: submissions
  ports:
  - name: tcp
    port: 5006
    targetPort: 5006
  - name: metrics
    port: 9006
    targetPort: 9006
