apiVersion: apps/v1
kind: Deployment
metadata:
  name: submissions-deployment
  namespace: oj
spec:
  selector:
    matchLabels:
      app: submissions
  template:
    metadata:
      labels:
        app: submissions
    spec:
      containers:
      - name: submissions-backend
        image: naman22a/leetcode-submissions-service:cedb29b6f36eba5cb1510660711609797bdbef66
        imagePullPolicy: Always
        ports:
        - containerPort: 5006
        - containerPort: 9006
        envFrom:
        - secretRef:
            name: oj-env
