apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: oj
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client-frontend
        image: naman22a/leetcode-client:2e603318006b84dc18238c3a7a48934e2cf7d20e
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
