apiVersion: apps/v1
kind: Deployment
metadata:
  name: tags-deployment
  namespace: oj
spec:
  selector:
    matchLabels:
      app: tags
  template:
    metadata:
      labels:
        app: tags
    spec:
      containers:
      - name: tags-backend
        image: naman22a/leetcode-tags-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5004
        envFrom:
        - secretRef:
            name: oj-env
