apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies-deployment
  namespace: oj
spec:
  selector:
    matchLabels:
      app: companies
  template:
    metadata:
      labels:
        app: companies
    spec:
      containers:
      - name: companies-backend
        image: naman22a/leetcode-companies-service:cedb29b6f36eba5cb1510660711609797bdbef66
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
        envFrom:
        - secretRef:
            name: oj-env
