name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml

    docker-build-and-push:
      needs: [code-quality, secrets-scan, dependency-scan, docker-scan]
      uses: ./.github/workflows/docker-build-and-push.yml
      secrets: inherit
