name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml

    docker-build-and-push:
      needs: [secrets-scan, docker-scan]
      uses: ./.github/workflows/docker-build-and-push.yml
      secrets: inherit
